language: generic
dist: xenial

# Cache Rust installation
cache:
  directories:
    - /home/travis/.cargo/
    - /home/travis/.rustup/

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

env:
  - PYENV_VERSION=3.5
before_install:
  - pyenv install $PYENV_VERSION
  - pyenv global $PYENV_VERSION
install:
  - pip3 install --user -r requirements.txt

script: ./build.sh

notifications:
  email: false
